---
development:
  cloud_name: readthat
  api_key: '893869429663796'
  api_secret: ULwCPyhNtW705KvnNtLMiLrti6I
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: readthat
  api_key: '893869429663796'
  api_secret: ULwCPyhNtW705KvnNtLMiLrti6I
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: readthat
  api_key: '893869429663796'
  api_secret: ULwCPyhNtW705KvnNtLMiLrti6I
  enhance_image_tag: true
  static_file_support: false
