export const FETCH_POSTS = 'FETCH_POSTS';

export const NEW_POST = 'NEW_POST';

export const SELECT_POSTS = 'SELECT_POSTS';

export const CLEAR_POST_SELECTION = 'CLEAR_POST_SELECTION';

export const FETCH_COMMENTS = 'FETCH_COMMENTS';

export const NEW_COMMENT = 'NEW_COMMENT';

export const FETCH_VOTES = 'FETCH_VOTES';

export const NEW_VOTE = 'NEW_VOTE';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';

export const NEW_CATEGORY = 'NEW_CATEGORY';

export const SELECT_CATEGORIES = 'SELECT_CATEGORIES';